[project]
name = "hqtechtalk-static-website"
version = "0.1.0"
description = "HQTechTalk - Static Technology News Website"
requires-python = ">=3.11"
dependencies = [
    # Static website - no server dependencies needed
]
